try{
    console.log(naoExiste);
} catch (err) {
    console.log("Variável naoExiste não foi criada");
    //err -> Está com o erro armazenado
}

